### ISSUE TITLE
Reg: Input shape of TFLite model is different from the Spleeter Model

### ISSUE THREAD

**Issue by VVasanth** [jinay1991/spleeter#2]
Hi Jinay,

When I load the TFLite 2stems model into TFLite Interpreter of Python and check the input shape - it is being shown as [1,2]. Whereas the input shape of the Spleeter model in checkpoint version is '(?, 2049, 2)'.

I am seeing this discrepancy and with this I could not proceed with utilizing TFlite model. Could you please throw some light on this?

Also, have you used the TFLite model in python environment with TFLite interpreter to separate the audio files?

Thanks,
V.Vasanth

**Comment by jinay1991** [comment]
Hello @VVasanth 

Yes you are correct. Input Tensor `waveform:0` is a dynamic tensor and hence it needs to be allocated before use. Please refer [this](https://github.com/jinay1991/spleeter/blob/c7be0be8f471a49396bc2f067cfe6913d3bf32c4/spleeter/inference_engine/tflite_inference_engine.cpp#L96) function to understand Input Processing pipeline with TFLite. You will need to use `Interpreter::ResizeInputTensor` (C++) or equivalent Python API to resize Input and Output Tensors.

This is due to the fact that Input/Output are of dims [samples, channels] where samples can be different for different audio files (depending on the length of audio file) and channel can be 2 for stereo.

You do these changes and this will work. You can refer to my C++ implementation and similar implementation you can make in Python TFLite API.

**Comment by RufusMall** [comment]
Hey @jinay1991 thanks for sharing such fabulous work.

Anyway I think you are actually wrong in one aspect of what you said above: You don't have to call allocate or resize the the OUTPUT tensors.

https://www.tensorflow.org/lite/guide/inference for TFLite you can see non of the examples attempt to allocate the output tensors even though they allocate the input tensors (they don't allocate output in any of the examples for any of the programming languages). 

Alas I am too stupid to find the actual Documentation/API reference for CPP but you can see from the header of the C version:
<img width="600" alt="Screenshot 2020-11-26 at 22 54 44" src="https://user-images.githubusercontent.com/2643977/100395825-62472c00-303a-11eb-9f40-4cf2f2ce8a75.png">

"// Updates allocations for all tensors, resizing dependent tensors using the
// specified input tensor dimensionality."

Output tensors are classed as "dependant" tensors

**Comment by jinay1991** [comment]
> Hey @jinay1991 thanks for sharing such fabulous work.
> 
> Anyway I think you are actually wrong in one aspect of what you said above: You don't have to call allocate or resize the the OUTPUT tensors.
> 
> https://www.tensorflow.org/lite/guide/inference for TFLite you can see non of the examples attempt to allocate the output tensors even though they allocate the input tensors (they don't allocate output in any of the examples for any of the programming languages).
> 
> Alas I am too stupid to find the actual Documentation/API reference for CPP but you can see from the header of the C version:
> <img alt="Screenshot 2020-11-26 at 22 54 44" width="600" src="https://user-images.githubusercontent.com/2643977/100395825-62472c00-303a-11eb-9f40-4cf2f2ce8a75.png">
> 
> "// Updates allocations for all tensors, resizing dependent tensors using the
> // specified input tensor dimensionality."
> 
> Output tensors are classed as "dependant" tensors.
> 
> edit: sorry just realised I commented non a closed issue, hope that doesn't make you hate me.

Hello @RufusMall According to documentation for [`ResizeInputTensor()`](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter#resizeinputtensor) - 
![resize_input_tensor](https://user-images.githubusercontent.com/9047750/100423511-63a14480-308c-11eb-8c77-dd7e3eeda0ea.png)
Note that here I use same API to resize Output Tensors at https://github.com/jinay1991/spleeter/blob/0b0fe947dd79983e9c0579e96d0c72206ae213be/spleeter/inference_engine/tflite_inference_engine.cpp#L143 & https://github.com/jinay1991/spleeter/blob/0b0fe947dd79983e9c0579e96d0c72206ae213be/spleeter/inference_engine/tflite_inference_engine.cpp#L147

**Comment by RufusMall** [comment]
Ahhh ok Looks like I was totally wrong :D. Thanks for the explanation!

Cheers :)
