### ISSUE TITLE
Hello, how can I generate a callable dynamic library (so file) from spleeter C++?

### ISSUE THREAD

**Issue by KangChou** [jinay1991/spleeter#3]
Reference project：

[https://github.com/FaceOnLive/Spleeter-Android-iOS](https://github.com/FaceOnLive/Spleeter-Android-iOSl)

https://github.com/deezer/spleeter

https://github.com/gvne/spleeterpp

**Comment by jinay1991** [comment]
This repository contains the C++ port of Spleeter. Can be compiled using following command: 

```bash
$ bazel build //spleeter/spleeter:spleeter
```

If you want to generate tarball containing all the headers and libraries, use following command:

```bash
$ bazel build //:spleeter-dev
```

this tarball shall be available for you to use under `bazel-bin` directory (which is present on your root directory of the repository)

**Comment by KangChou** [comment]
> 此存储库包含 Spleeter 的 C++ 端口。可以使用以下命令编译库：
> 
> ```shell
> $ bazel build //spleeter/spleeter:spleeter
> ```
> 
> 如果要生成包含所有头文件和库的 tarball，请使用以下命令：
> 
> ```shell
> $ bazel build //:spleeter-dev
> ```
> 
> 此 tarball 应在`bazel-bin`目录中可用（位于存储库的根目录中）
> 
> 或者，您也可以使用https://github.com/jinay1991/spleeter/releases/download/v1.4/spleeter-dev.tar.gz

Hello, thank you very much for the dynamic library you provided. I still have not successfully called the dynamic library. Can you share with me a demo that can input audio and separate the accompaniment, or a function interface, thank you, because I am currently doing this Research.

For methods called like this, can you directly write a function to call the dynamic library?

https://github.com/KangChou/deep_c_cc/blob/main/c_so_cpp2022/so_test2/test.cpp

**Comment by KangChou** [comment]
> 此存储库包含 Spleeter 的 C++ 端口。可以使用以下命令编译库：
> 
> ```shell
> $ bazel build //spleeter/spleeter:spleeter
> ```
> 
> 如果要生成包含所有头文件和库的 tarball，请使用以下命令：
> 
> ```shell
> $ bazel build //:spleeter-dev
> ```
> 
> 此 tarball 应在`bazel-bin`目录中可用（位于存储库的根目录中）
> 
> 或者，您也可以使用https://github.com/jinay1991/spleeter/releases/download/v1.4/spleeter-dev.tar.gz

How can I make use of it?  ----->libspleeter.so
```bash
void *handle = dlopen("/spleeter/lib/libspleeter.so", RTLD_LAZY);
```

**Comment by KangChou** [comment]
spleeter/bin# ./spleeter 
./spleeter: error while loading shared libraries: libavcodec.so.57: cannot open shared object file: No such file or directory

**Comment by jinay1991** [comment]
This is done through Bazel Build System (If you don't know, I strongly recommend going through basics on that to understand this repo's build steps => https://bazel.build/start). Library is built here -> https://github.com/jinay1991/spleeter/blob/ae21059a369b8d13da7b5581fc8b7b5cb5ac9ec8/spleeter/BUILD#L7

**Comment by KangChou** [comment]
@jinay1991

**Comment by KangChou** [comment]
> You will of course need dependencies installed on your system (i.e.`ffmpeg`)
> 
> https://github.com/jinay1991/spleeter#dev-environment

![image](https://user-images.githubusercontent.com/36963108/162933069-7e3f9270-7dc4-4c2b-a0f3-fa996cd68e45.png)

**Comment by KangChou** [comment]
> You will of course need dependencies installed on your system (i.e.`ffmpeg`)
> 
> https://github.com/jinay1991/spleeter#dev-environment

Although I have configured the environment variables, I still get the error

(export PATH=$PATH:/usr/bin/
export PATH=$PATH:/usr/bin/ffmpeg/bin
export PATH=$PATH:/usr/bin/ffmpeg)

Also, the development environment I use is based on your:
docker pull registry.gitlab.com/jinay1991/spleeter

**Comment by KangChou** [comment]
> You will of course need dependencies installed on your system (i.e.`ffmpeg`)
> 
> https://github.com/jinay1991/spleeter#dev-environment

After searching, it is found that the dynamic library in your docker environment is:
```bash
find / -name libavcodec.so.5*
/usr/lib/x86_64-linux-gnu/libavcodec.so.58
/usr/lib/x86_64-linux-gnu/libavcodec.so.58.54.100
```

Is the executable file to be recompiled or solved in any way?

**Comment by KangChou** [comment]
> You will of course need dependencies installed on your system (i.e.`ffmpeg`)
> 
> https://github.com/jinay1991/spleeter#dev-environment

The error reporting problem of the dynamic library libavcodec.so.57 has been resolved：[https://github.com/KangChou/deepcv_project_demo/tree/main/dynamic_library](https://github.com/KangChou/deepcv_project_demo/tree/main/dynamic_library) \
[https://github.com/KangChou/spleeter_dynamic_library](https://github.com/KangChou/spleeter_dynamic_library)

**Comment by jinay1991** [comment]
As you also want to build the Android App using this Project, it is worth checking with reporter of this issue (he was the early adopter of this approach and already succeed) -https://github.com/jinay1991/spleeter/issues/1

**Comment by jinay1991** [comment]
> > 这是通过 Bazel 构建系统完成的（如果您不知道，我强烈建议您通过基础知识来了解此 repo 的构建步骤 => [https://bazel.build/start）。图书馆建在这里->](https://bazel.build/start%EF%BC%89%E3%80%82%E5%9B%BE%E4%B9%A6%E9%A6%86%E5%BB%BA%E5%9C%A8%E8%BF%99%E9%87%8C-%3E)
> > https://github.com/jinay1991/spleeter/blob/ae21059a369b8d13da7b5581fc8b7b5cb5ac9ec8/spleeter/BUILD#L7
> 
> My current questions are summarized as follows:
> 
> I want to use the spleeter to deploy on the Android side, and I hope that the interface of the spleeter c++ dynamic library can be called. At present, the dynamic library you gave still cannot be called.
> 
> What I want to know is the dynamic library you just gave, how can I use the C++ program to call it and realize the separation of the vocal accompaniment of music?
> 
> Because I want to deploy it on mobile android, although I have tried the method on android, but it doesn't seem to work.

As you also want to build the Android App using this Project, it is worth checking with reporter of this issue (he was the early adopter of this approach and already succeed) -https://github.com/jinay1991/spleeter/issues/1

**Comment by KangChou** [comment]
> ```shell
>  bazel build //:spleeter-dev
> ```

```bash
./spleeter
ERROR: Could not open 'external/models/5stems/5stems.tflite'.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0414 05:05:39.348709 10648 tflite_inference_engine.cpp:70] Check failed: model_ Failed to read model external/models/5stems/5stems.tflite
*** Check failure stack trace: ***
Aborted (core dumped)


```

**Comment by KangChou** [comment]
> This repository contains the C++ port of Spleeter. libraries can be compiled using following command:
> 
> ```shell
> $ bazel build //spleeter/spleeter:spleeter
> ```
> 
> If you want to generate tarball containing all the headers and libraries, use following command:
> 
> ```shell
> $ bazel build //:spleeter-dev
> ```
> 
> this tarball shall be available at `bazel-bin` directory (which is present on your root directory of the repository)
> 
> Alternatively, you can also use https://github.com/jinay1991/spleeter/releases/download/v1.4/spleeter-dev.tar.gz

```
ERROR: Could not open 'external/models/5stems/5stems.tflite'.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0414 05:05:39.348709 10648 tflite_inference_engine.cpp:70] Check failed: model_ Failed to read model external/models/5stems/5stems.tflite
*** Check failure stack trace: ***
Aborted (core dumped)

```

**Comment by KangChou** [comment]
@oluwabajio 

[https://github.com/jinay1991/spleeter/issues/10](https://github.com/jinay1991/spleeter/issues/10)

**Comment by KangChou** [comment]
> ```
> ERROR: Could not open 'external/models/5stems/5stems.tflite'.
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0414 05:05:39.348709 10648 tflite_inference_engine.cpp:70] Check failed: model_ Failed to read model external/models/5stems/5stems.tflite
> *** Check failure stack trace: ***
> Aborted (core dumped)
> ```
> 
> #10


The current issue is resolved. [KangChou/spleeter](https://github.com/KangChou/spleeter_dynamic_library)

@jinay1991
@oluwabajio
