### ISSUE TITLE
Spleeter_dynamic_library: Solutions and steps to implement the executable file of the algorithm

### ISSUE THREAD

**Issue by KangChou** [jinay1991/spleeter#7]
Spleeter(C++)_dynamic_library: Solutions and steps to implement the executable file of the algorithm

https://github.com/KangChou/spleeter_dynamic_library

**Comment by jinay1991** [comment]
What do you expect in this reported Issue?

**Comment by KangChou** [comment]
> What do you expect in this reported Issue?

It is hoped that the project can be deployed on the Android side, and the GPU is also expected to be used for prompts on the problem of model inference speed, hoping to further deepen cooperation.

**Comment by jinay1991** [comment]
There are already lots of efforts and contributions available for Android Side, one them is https://github.com/FaceOnLive/Spleeter-Android-iOS

**Comment by KangChou** [comment]
> There are already lots of efforts and contributions available for Android Side, one them is https://github.com/FaceOnLive/Spleeter-Android-iOS
> 
> This repo's goal was never to build Android App. It is Library port (Generic) for general use.

Unfortunately, the Android version is paid, I would like to implement the process from source build to deployment.

**Comment by jinay1991** [comment]
Solution steps and implementation of executable is already provided in README.md. Support for Android App is not scope of this repo. Though it is highly encouraged to contribute App version of code as PR if you like. I close this issue.
