### ISSUE TITLE
I changed how to use the following example to compile the executable problem, and how should the location of the project directory be stored in the specified path ？

### ISSUE THREAD

**Issue by KangChou** [jinay1991/spleeter#8]
I changed how to use the following example to compile the executable problem, and how should the location of the project directory be stored in the specified path ？

**Comment by KangChou** [comment]
![image](https://user-images.githubusercontent.com/36963108/163301270-031d1d12-2c40-4039-8ca8-afc12408c574.png)

**Comment by jinay1991** [comment]
Can you please elaborate the issue? It is unclear to me what is issue here.
